name = "kawaltransaksi-api"
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "api.kawaltransaksi.com", custom_domain = true }
]

[vars]
NODE_ENV = "production"
FRONTEND_URL = "https://kawaltransaksi.com"
FRONTEND_URL_CLONE = "https://kawaltransaksi-605520424162.asia-southeast1.run.app"
ADMIN_EMAIL = "kawaltransaksi@gmail.com"
R2_PUBLIC_URL = "https://cdn.kawaltransaksi.com"

[[kv_namespaces]]
binding = "LIMITER"
id = "a218c09fba30472abde923a131764ba0"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "kawaltransaksi"

[[unsafe.bindings]]
name = "AUTH_RATE_LIMITER"
type = "ratelimit"
namespace_id = "1001"
simple = { limit = 100, period = 60 }

[triggers]
crons = [
  "0 23 * * SUN",
  "*/30 * * * *",
  "0 * * * *",
  "0 19 * * *",
]